Add --reset flag to deploy task
NomicFoundation/hardhat-ignition pull request #651
Opened 2023-12-12 03:23 UTC by zoeyTM

Adds a `--reset` flag to wipe the deployments state before a deployment. Also includes a confirmation when used on a non-hardhat network.

resolves #649

2023-12-12 03:26 UTC, zoeyTM commented
<img width="742" alt="Screen Shot 2023-12-11 at 10 24 18 PM" src="https://github.com/NomicFoundation/hardhat-ignition/assets/14796043/f36867d8-2aa4-41a2-b8f4-ad5468707f0d">

2023-12-14 11:02 UTC, kanej commented on packages/hardhat-plugin-viem/scripts/compile-test-fixture-projects.ts
> -    if (fs.existsSync(path.join(fixtureProjectDir, "./artifacts"))) {
Was this causing an issue?

The intent was that you only need to do a precompile of the fixture projects to get the viem package build working once - to generate the contract type information. Is there a case I didn't understand?

2023-12-14 11:04 UTC, kanej commented on packages/hardhat-plugin/src/index.ts
>          const prompt = await Prompt({
Not for this PR. I think we should look at removing the prompt dependency. We are doing enough low level console work to justify putting in the equivalent to let us drop a dep.

2023-12-14 11:45 UTC, kanej requested changes
Looks good.

Can I request two changes:

1. Can you add an `@nomicfoundation/hardhat-plugin` file based project integration test that: runs a deployment that succeeds, then reruns a deployment modified in such a way (e.g. same future id but different contract) it would be blocked if rerun. But will succeed when run with the reset flag.
2. Can you add a warning message and cancel if you run reset with an in-memory deployment.

If you have a different approach for the test we should consider it as I suspect we might run a fowl of the clearLine bug.

2023-12-18 12:20 UTC, kanej commented on packages/hardhat-plugin-viem/scripts/compile-test-fixture-projects.ts
> -    if (fs.existsSync(path.join(fixtureProjectDir, "./artifacts"))) {
Out of band we discussed and agreed to remove the line.

If you are making changes to the viem tests this can lead to odd results.

2023-12-18 13:56 UTC, kanej commented on packages/hardhat-plugin/test/test-helpers/use-ignition-project.ts
> +        `../fixture-projects/${fixtureProjectName}/ignition`
Well ...

2023-12-18 13:57 UTC, kanej approved these changes

2023-12-18 13:58 UTC, kanej commented
I have done of manual tests. No issues against local/sepolia.

2023-12-18 14:03 UTC, merged